[phases.setup]
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "pip install -r backend/requirements.txt"]

[start]
cmd = "python3 -m backend.run"
